# Use Dash Case...

# Root Directory
## NOTE! This code assumes you are running this tools from /DataAquisition/gregoryb/
root-directory: "."

# Record Dump Database
mongo-dump-db:
  dump-db-username: "lafWebScrapeCS470"
  dump-db-password: "ajnHxsiFYEZ13UkC"
  dump-db-mongo-uri: "mongodb+srv://lafWebScrapeCS470:ajnHxsiFYEZ13UkC@webscrapedump.jugak.mongodb.net/?retryWrites=true&w=majority&appName=WebScrapeDump"
  dump-db-name: "WebScrapeDumpDB"
  dump-db-collection: "WebScrapeDump"

# Log Files
logging-utils:
  # Log Directory
  log-dir: "./Logs/"

  # Log Files and Relevant Properties
  file-handlers:
  # Overall File Handler
  - level: "DEBUG"
    filename: "scrape-log-debug.log"
    encoding: "utf-8"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # Error File Handler
  - level: "ERROR"
    filename: "scrape-log-error.log"
    encoding: "utf-8"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Emergency Source Dump
emergency-dump:
  emergency-dump-dir: "./Logs/SourceDump/"

# Chrome Utilities
chrome-utils:
  # Chrome Binary Path
  chrome-path: "./Build/bin/chrome-linux64/chrome"
  chrome-driver-path: "./Build/bin/chromedriver-linux64/chromedriver"
  chrome-options:
  - "--headless" # Remove this if you want to see the browser during simulation
  - "--no-sandbox"
  experimental-chrome-options:
    download.default_directory: "./Logs/TempEmpty/" # Default download directory
    download.prompt_for_download: false # Disable download prompt
    download.directory_upgrade: true # Allow directory upgrade
    download.safebrowsing.enabled: false # Disable safe browsing
    profile.default_content_setting_values.automatic_downloads: 1 # Allow automatic downloads
  address-search-url: "https://www.ncpub.org/_web/Search/Disclaimer.aspx?FromUrl=../search/commonsearch.aspx?mode=address"
  advanced-search-url: "..."
